import path from 'node:path';
import type { ConfigEntry } from '@rac/shared';
import { envPath } from '../services/env-path.js';

type UrlProtocol = 'http:' | 'https:' | 'ws:' | 'wss:';

export type ConfigFieldDefinition = Omit<ConfigEntry, 'value' | 'configured' | 'source'> & {
  defaultValue?: string;
  min?: number;
  max?: number;
  urlProtocols?: readonly UrlProtocol[];
};

const defaultDbPath = path.resolve(path.dirname(envPath), 'data', 'rac.db');

export const CONFIG_FIELDS: ConfigFieldDefinition[] = [
  {
    key: 'NODE_ENV',
    label: 'Node environment',
    description: 'Runtime environment mode for the host process.',
    group: 'host',
    kind: 'select',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
    options: [
      { value: 'development', label: 'development' },
      { value: 'production', label: 'production' },
      { value: 'test', label: 'test' },
    ],
  },
  {
    key: 'HOST_PORT',
    label: 'Host port',
    description: 'Port used by the API host service.',
    group: 'host',
    kind: 'number',
    required: true,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: '3001',
    min: 1,
    max: 65535,
  },
  {
    key: 'HOST_HOSTNAME',
    label: 'Bind address',
    description: 'Use 127.0.0.1 for local access, or 0.0.0.0 when exposing the host service.',
    group: 'host',
    kind: 'string',
    required: true,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: '127.0.0.1',
  },
  {
    key: 'PUBLIC_BASE_URL',
    label: 'Public base URL',
    description: 'The URL users and notification links should use to reach this console.',
    group: 'host',
    kind: 'url',
    required: true,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: 'http://localhost:3001',
  },
  {
    key: 'HOST_DEVICE_NAME',
    label: 'Host device name',
    description: 'Display name reported by the built-in host device.',
    group: 'host',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'HOST_DEVICE_PLATFORM',
    label: 'Host device platform',
    description: 'Platform string reported by the built-in host device.',
    group: 'host',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'HOST_DEVICE_FINGERPRINT',
    label: 'Host device fingerprint',
    description:
      'Stable fingerprint for the built-in host device. Changing it creates a new device identity.',
    group: 'host',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'CORS_ORIGINS',
    label: 'Allowed web origins',
    description: 'Comma-separated browser origins allowed to call the API.',
    group: 'host',
    kind: 'csv',
    required: true,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: 'http://localhost:5173,http://127.0.0.1:5173',
  },
  {
    key: 'VITE_API_URL',
    label: 'Web API URL',
    description: 'Build-time API base URL used by the web console.',
    group: 'web',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'web',
    defaultValue: 'http://127.0.0.1:3001',
  },
  {
    key: 'VITE_SSE_URL',
    label: 'Web SSE URL',
    description:
      'Build-time SSE base URL used by the web console. Leave blank to derive from VITE_API_URL.',
    group: 'web',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'web',
  },
  {
    key: 'VITE_WS_URL',
    label: 'Web WebSocket URL',
    description:
      'Build-time WebSocket base URL used by the web console. Leave blank to derive from browser location.',
    group: 'web',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'web',
    urlProtocols: ['ws:', 'wss:'],
    placeholder: 'ws://127.0.0.1:3001',
  },
  {
    key: 'DB_PATH',
    label: 'Database path',
    description: 'SQLite database file path used by the host service.',
    group: 'host',
    kind: 'file',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: defaultDbPath,
  },
  {
    key: 'REQUIRE_HTTPS',
    label: 'Require HTTPS',
    description: 'Reject plain HTTP requests. Keep this off for local development.',
    group: 'host',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'TRUST_PROXY',
    label: 'Trust reverse proxy',
    description:
      'Enable when the service is behind a trusted reverse proxy that sets forwarded headers.',
    group: 'host',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'AGENT_SECURITY_PROFILE',
    label: 'Agent security profile',
    description: 'Use strict for public or HTTPS deployments; local keeps development defaults.',
    group: 'security',
    kind: 'select',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: 'local',
    options: [
      { value: 'local', label: 'local' },
      { value: 'strict', label: 'strict' },
    ],
  },
  {
    key: 'LOG_REDACTION_ENABLED',
    label: 'Enable log redaction',
    description:
      'Redact common secret patterns before logs, exports, and audit messages are stored or returned.',
    group: 'logging',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: 'true',
  },
  {
    key: 'LOG_LEVEL',
    label: 'Log level',
    description: 'Minimum host log level.',
    group: 'logging',
    kind: 'select',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: 'info',
    options: [
      { value: 'trace', label: 'trace' },
      { value: 'debug', label: 'debug' },
      { value: 'info', label: 'info' },
      { value: 'warn', label: 'warn' },
      { value: 'error', label: 'error' },
      { value: 'fatal', label: 'fatal' },
      { value: 'silent', label: 'silent' },
    ],
  },
  {
    key: 'LOG_FORMAT',
    label: 'Log format',
    description: 'Use json for structured logs, or leave default for terminal-friendly output.',
    group: 'logging',
    kind: 'select',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
    options: [
      { value: 'pretty', label: 'pretty' },
      { value: 'json', label: 'json' },
    ],
  },
  {
    key: 'LOG_PRETTY',
    label: 'Pretty logs',
    description: 'Force pretty or JSON log transport regardless of terminal detection.',
    group: 'logging',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'REMOTE_REGISTRATION_TOKEN',
    label: 'Remote registration token',
    description:
      'Shared registration secret required before issuing remote worker credentials in strict deployments.',
    group: 'security',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
    min: 32,
  },
  {
    key: 'ADMIN_USERNAME',
    label: 'Admin username',
    description: 'Initial admin username used during bootstrap.',
    group: 'auth',
    kind: 'string',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: 'admin',
  },
  {
    key: 'ADMIN_PASSWORD',
    label: 'Admin password',
    description:
      'Initial admin password. Existing users keep their stored password after bootstrap.',
    group: 'auth',
    kind: 'secret',
    required: true,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
    min: 12,
  },
  {
    key: 'JWT_SECRET',
    label: 'Session signing secret',
    description:
      'Stable secret for login sessions. Set this to avoid invalid tokens after restart.',
    group: 'auth',
    kind: 'secret',
    required: true,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
    min: 32,
  },
  {
    key: 'ACCESS_TOKEN_TTL_SECONDS',
    label: 'Session lifetime',
    description: 'How long browser login sessions remain valid.',
    group: 'auth',
    kind: 'number',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: '43200',
    min: 60,
    max: 2592000,
  },
  {
    key: 'AUTH_COOKIE_NAME',
    label: 'Auth cookie name',
    description: 'Cookie name used for browser sessions.',
    group: 'auth',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'rac_access_token',
  },
  {
    key: 'AUTH_COOKIE_SECURE',
    label: 'Secure auth cookie',
    description: 'Only send login cookies over HTTPS. Disable for local HTTP development.',
    group: 'auth',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'AUTH_COOKIE_SAME_SITE',
    label: 'Cookie same-site policy',
    description: 'Controls cross-site browser cookie behavior.',
    group: 'auth',
    kind: 'select',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: 'lax',
    options: [
      { value: 'lax', label: 'lax' },
      { value: 'strict', label: 'strict' },
      { value: 'none', label: 'none' },
    ],
  },
  {
    key: 'ALLOW_QUERY_TOKEN_AUTH',
    label: 'Allow query token auth',
    description:
      'Allow access tokens to be supplied via query parameters. Keep this off for public deployments.',
    group: 'auth',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'LOGIN_RATE_LIMIT_MAX_ATTEMPTS',
    label: 'Login rate limit attempts',
    description: 'Maximum failed login attempts allowed before lockout.',
    group: 'auth',
    kind: 'number',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: '5',
    min: 1,
    max: 50,
  },
  {
    key: 'LOGIN_RATE_LIMIT_WINDOW_SECONDS',
    label: 'Login rate limit window',
    description: 'Duration in seconds for counting failed login attempts.',
    group: 'auth',
    kind: 'number',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: '60',
    min: 10,
    max: 3600,
  },
  {
    key: 'LOGIN_RATE_LIMIT_LOCKOUT_SECONDS',
    label: 'Login lockout duration',
    description: 'Lockout duration in seconds after exceeding rate limit attempts.',
    group: 'auth',
    kind: 'number',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: '300',
    min: 0,
    max: 86400,
  },
  {
    key: 'LOGIN_RATE_LIMIT_EXEMPT_LOOPBACK',
    label: 'Exempt loopback from lockout',
    description:
      'When enabled, requests from loopback addresses are exempt from lockout enforcement.',
    group: 'auth',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'true',
  },
  {
    key: 'ALLOWED_WORK_DIR',
    label: 'Allowed working directory',
    description: 'Optional directory boundary for agent run workspaces.',
    group: 'task',
    kind: 'directory',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    placeholder: 'D:\\Data\\Projects',
  },
  {
    key: 'RAC_CONTROLLER_URL',
    label: 'Remote worker controller URL',
    description: 'Controller URL used when this process runs as a remote worker.',
    group: 'remote',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
  },
  {
    key: 'REMOTE_CONTROLLER_URL',
    label: 'Remote controller URL legacy alias',
    description: 'Legacy alias for RAC_CONTROLLER_URL.',
    group: 'remote',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
    advanced: true,
  },
  {
    key: 'RAC_REMOTE_REGISTRATION_TOKEN',
    label: 'Remote worker registration token',
    description: 'Registration token presented by a remote worker to a strict controller.',
    group: 'remote',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    restartTarget: 'worker',
    placeholder: 'Leave blank to keep the current value',
    min: 32,
  },
  {
    key: 'RAC_REMOTE_DEVICE_ID',
    label: 'Remote worker device ID',
    description: 'Persisted device ID returned after remote worker registration.',
    group: 'remote',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
  },
  {
    key: 'RAC_REMOTE_DEVICE_TOKEN',
    label: 'Remote worker device token',
    description: 'Persisted device token returned after remote worker registration.',
    group: 'remote',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    restartTarget: 'worker',
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'RAC_REMOTE_DEVICE_NAME',
    label: 'Remote worker device name',
    description: 'Display name reported by a remote worker.',
    group: 'remote',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
  },
  {
    key: 'RAC_REMOTE_DEVICE_PLATFORM',
    label: 'Remote worker platform',
    description: 'Platform string reported by a remote worker.',
    group: 'remote',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
    advanced: true,
  },
  {
    key: 'RAC_REMOTE_DEVICE_FINGERPRINT',
    label: 'Remote worker fingerprint',
    description: 'Stable fingerprint for a remote worker device identity.',
    group: 'remote',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
    advanced: true,
  },
  {
    key: 'RAC_REMOTE_ALLOWED_WORK_DIR',
    label: 'Remote worker workspace root',
    description:
      'Workspace boundary used by a remote worker. Falls back to ALLOWED_WORK_DIR when unset.',
    group: 'remote',
    kind: 'directory',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
    placeholder: '/home/user/projects',
  },
  {
    key: 'RAC_REMOTE_POLL_INTERVAL_MS',
    label: 'Remote worker poll interval legacy alias',
    description: 'Legacy alias for RAC_REMOTE_HEARTBEAT_INTERVAL_MS.',
    group: 'remote',
    kind: 'number',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
    advanced: true,
    min: 1000,
    max: 60000,
  },
  {
    key: 'RAC_REMOTE_HEARTBEAT_INTERVAL_MS',
    label: 'Remote worker heartbeat interval',
    description: 'How often a remote worker reports health and checks for tasks.',
    group: 'remote',
    kind: 'number',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
    defaultValue: '3000',
    min: 1000,
    max: 60000,
  },
  {
    key: 'RAC_REMOTE_MAX_RECONNECT_DELAY_MS',
    label: 'Remote worker max reconnect delay',
    description: 'Maximum WebSocket bridge reconnect backoff for remote workers.',
    group: 'remote',
    kind: 'number',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'worker',
    defaultValue: '30000',
    min: 1000,
    max: 300000,
  },
  {
    key: 'RAC_REMOTE_BRIDGE_PING_INTERVAL_MS',
    label: 'Remote bridge ping interval',
    description: 'How often the Host pings remote worker workspace bridges.',
    group: 'remote',
    kind: 'number',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: '15000',
    min: 5000,
    max: 300000,
  },
  {
    key: 'APPROVAL_TIMEOUT_SECONDS',
    label: 'Approval timeout',
    description:
      'Startup default for how long a run can wait for manual approval. The Settings page can override this at runtime without restart.',
    group: 'task',
    kind: 'number',
    required: true,
    secret: false,
    restartRequired: false,
    defaultValue: '120',
    min: 10,
    max: 3600,
  },
  {
    key: 'TASK_MAX_DURATION_SECONDS',
    label: 'Run max duration',
    description: 'Maximum runtime for a single run before it is considered stuck.',
    group: 'task',
    kind: 'number',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: '1800',
    min: 60,
    max: 86400,
  },
  {
    key: 'CODEX_ENABLED',
    label: 'Enable Codex executor',
    description: 'Enable or disable the local Codex CLI executor.',
    group: 'executors',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'true',
  },
  {
    key: 'CODEX_COMMAND',
    label: 'Codex command',
    description: 'Command used to start Codex.',
    group: 'executors',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'codex',
  },
  {
    key: 'CODEX_MODEL',
    label: 'Codex model',
    description: 'Optional model override for Codex runs.',
    group: 'executors',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'CLAUDE_MODEL',
    label: 'Claude model',
    description: 'Default Claude API model used by the Claude API executor.',
    group: 'executors',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'claude-sonnet-4-6',
  },
  {
    key: 'CLAUDE_MAX_TOKENS',
    label: 'Claude max tokens',
    description: 'Maximum output tokens for Claude API executor requests.',
    group: 'executors',
    kind: 'number',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: '8192',
    min: 256,
    max: 200000,
  },
  {
    key: 'CLAUDE_MAX_TOOL_ROUNDS',
    label: 'Claude max tool rounds',
    description: 'Maximum tool rounds allowed for Claude API executor runs.',
    group: 'executors',
    kind: 'number',
    required: true,
    secret: false,
    restartRequired: true,
    defaultValue: '30',
    min: 1,
    max: 200,
  },
  {
    key: 'CODEX_FULL_AUTO',
    label: 'Codex full-auto legacy flag',
    description:
      'Deprecated compatibility flag. Workbench uses Codex official sandbox and approval presets instead.',
    group: 'executors',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'OPENAI_API_KEY',
    label: 'OpenAI API key',
    description: 'Optional API key passed to Codex when needed.',
    group: 'executors',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'OPENAI_BASE_URL',
    label: 'OpenAI base URL',
    description: 'Optional OpenAI-compatible base URL used for environment provider profiles.',
    group: 'providers',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'OPENAI_MODELS',
    label: 'OpenAI models',
    description: 'Comma-separated model IDs exposed by the OpenAI environment provider profile.',
    group: 'providers',
    kind: 'csv',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'OPENROUTER_API_KEY',
    label: 'OpenRouter API key',
    description: 'Optional API key used to create the OpenRouter environment provider profile.',
    group: 'providers',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    restartTarget: 'host',
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'OPENROUTER_BASE_URL',
    label: 'OpenRouter base URL',
    description: 'Optional OpenRouter-compatible base URL.',
    group: 'providers',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'OPENROUTER_MODELS',
    label: 'OpenRouter models',
    description:
      'Comma-separated model IDs exposed by the OpenRouter environment provider profile.',
    group: 'providers',
    kind: 'csv',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'ANTHROPIC_BASE_URL',
    label: 'Anthropic base URL',
    description: 'Optional Anthropic-compatible base URL.',
    group: 'providers',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'ANTHROPIC_MODELS',
    label: 'Anthropic models',
    description: 'Comma-separated model IDs exposed by the Anthropic environment provider profile.',
    group: 'providers',
    kind: 'csv',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'CLAUDE_MODELS',
    label: 'Claude models legacy alias',
    description: 'Legacy alias for ANTHROPIC_MODELS.',
    group: 'providers',
    kind: 'csv',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'OLLAMA_BASE_URL',
    label: 'Ollama base URL',
    description: 'Optional Ollama base URL used to create an environment provider profile.',
    group: 'providers',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
  },
  {
    key: 'OLLAMA_API_KEY',
    label: 'Ollama API key',
    description: 'Optional API key for secured Ollama-compatible endpoints.',
    group: 'providers',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    restartTarget: 'host',
    placeholder: 'Leave blank to keep the current value',
    advanced: true,
  },
  {
    key: 'OLLAMA_MODELS',
    label: 'Ollama models',
    description: 'Comma-separated model IDs exposed by the Ollama environment provider profile.',
    group: 'providers',
    kind: 'csv',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'PROVIDER_SECRET_KEY',
    label: 'Provider secret key',
    description:
      'Master key used to encrypt Provider API keys stored in the control plane database.',
    group: 'providers',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
    min: 32,
  },
  {
    key: 'AI_SERVICE_URL',
    label: 'AI service URL',
    description:
      'Local FastAPI service used for RAG indexing, retrieval, evaluation helpers, and failure analysis.',
    group: 'providers',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'http://127.0.0.1:8010',
  },
  {
    key: 'AGENT_MODEL_PRICING_JSON',
    label: 'Model pricing JSON',
    description:
      'Optional JSON map used to show model usage cost only when all required token rates are present.',
    group: 'providers',
    kind: 'json',
    required: false,
    secret: false,
    restartRequired: true,
    placeholder: '{"model-id":{"inputPerMillion":0,"outputPerMillion":0,"currency":"USD"}}',
  },
  {
    key: 'GITEA_BASE_URL',
    label: 'Gitea base URL',
    description: 'Optional Gitea server URL used by MCP issue tools.',
    group: 'providers',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
    placeholder: 'https://gitea.example.com',
  },
  {
    key: 'GITEA_TOKEN',
    label: 'Gitea token',
    description: 'Optional access token used by MCP Gitea issue tools.',
    group: 'providers',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'CLAUDE_CODE_ENABLED',
    label: 'Enable Claude Code executor',
    description: 'Enable or disable the local Claude Code CLI executor.',
    group: 'executors',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'true',
  },
  {
    key: 'CLAUDE_CODE_COMMAND',
    label: 'Claude Code command',
    description: 'Command used to start Claude Code.',
    group: 'executors',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'claude',
  },
  {
    key: 'CLAUDE_CODE_SKIP_PERMISSIONS',
    label: 'Claude Code skip permissions',
    description:
      'Pass the skip-permissions flag to Claude Code. Disabled by default; enable only for trusted development worktrees.',
    group: 'executors',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'ANTHROPIC_API_KEY',
    label: 'Anthropic API key',
    description: 'API key used by Claude Code when required.',
    group: 'executors',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'CLAUDE_API_KEY',
    label: 'Claude API key',
    description: 'API key used by the Claude API executor.',
    group: 'executors',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'CLAUDE_CODE_MODEL',
    label: 'Claude Code model',
    description: 'Optional model override passed to Claude Code.',
    group: 'executors',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'CLAUDE_CODE_MAX_TURNS',
    label: 'Claude Code max turns',
    description: 'Optional maximum number of turns passed to Claude Code.',
    group: 'executors',
    kind: 'number',
    required: false,
    secret: false,
    restartRequired: true,
    min: 1,
    max: 200,
  },
  {
    key: 'CODEX_HOME',
    label: 'Codex home',
    description: 'Override the Codex home directory used for global config and session history.',
    group: 'runtime',
    kind: 'directory',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'CODEX_CONFIG_FILE',
    label: 'Codex config file',
    description: 'Override the Codex global config.toml path.',
    group: 'runtime',
    kind: 'file',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'CLAUDE_HOME',
    label: 'Claude home',
    description: 'Override the Claude home directory used for session history.',
    group: 'runtime',
    kind: 'directory',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'CLAUDE_SETTINGS_FILE',
    label: 'Claude settings file',
    description: 'Override the Claude global settings.json path.',
    group: 'runtime',
    kind: 'file',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'TERMINAL',
    label: 'Linux terminal command',
    description: 'Preferred terminal emulator command for launching native terminals on Linux.',
    group: 'runtime',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    advanced: true,
  },
  {
    key: 'RAC_CODEX_APP_SERVER_DISABLED',
    label: 'Disable Codex app-server bridge',
    description:
      'Force Codex sessions to use the legacy CLI fallback instead of the app-server bridge.',
    group: 'runtime',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: 'false',
    advanced: true,
  },
  {
    key: 'RAC_CLAUDE_AGENT_SDK_DISABLED',
    label: 'Disable Claude Agent SDK bridge',
    description:
      'Force Claude Code sessions to use the legacy CLI fallback instead of the Agent SDK bridge.',
    group: 'runtime',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: 'false',
    advanced: true,
  },
  {
    key: 'RAC_DISABLE_CLAUDE_AGENT_SDK',
    label: 'Disable Claude Agent SDK discovery',
    description:
      'Legacy switch used by provider runtime discovery to disable Claude Agent SDK loading.',
    group: 'runtime',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: 'false',
    advanced: true,
  },
  {
    key: 'RAC_ALLOW_UNSAFE_PROVIDER_APPROVAL_FALLBACK',
    label: 'Allow unsafe approval fallback',
    description:
      'Allow legacy CLI fallback executors to run default/auto-review sessions without provider-native runtime approvals.',
    group: 'runtime',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: 'false',
    advanced: true,
  },
  {
    key: 'CUSTOM_COMMAND_AGENT_ENABLED',
    label: 'Enable custom command agent',
    description:
      'Enable the Custom Command Agent executor. It always asks for approval before running the configured command.',
    group: 'executors',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'CUSTOM_COMMAND_AGENT_COMMAND',
    label: 'Custom command',
    description: 'Command or absolute path used by the Custom Command Agent.',
    group: 'executors',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    placeholder: 'node, python, or an internal agent wrapper',
  },
  {
    key: 'CUSTOM_AGENT_COMMAND',
    label: 'Custom command legacy alias',
    description:
      'Legacy alias for CUSTOM_COMMAND_AGENT_COMMAND. Prefer CUSTOM_COMMAND_AGENT_COMMAND for new installs.',
    group: 'executors',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'CUSTOM_COMMAND_AGENT_ARGS',
    label: 'Custom command args',
    description:
      'Comma-separated default arguments. {prompt}, {taskId}, and {workDir} placeholders are supported.',
    group: 'executors',
    kind: 'csv',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'CUSTOM_COMMAND_AGENT_TIMEOUT_SECONDS',
    label: 'Custom command timeout',
    description: 'Maximum runtime for the Custom Command Agent command.',
    group: 'executors',
    kind: 'number',
    required: false,
    secret: false,
    restartRequired: true,
    min: 10,
    max: 86400,
  },
  {
    key: 'WEBHOOK_URL',
    label: 'Webhook URL',
    description:
      'Startup default for the webhook target. The Settings page overrides this at runtime without restart.',
    group: 'notifications',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: false,
  },
  {
    key: 'WEBHOOK_SECRET',
    label: 'Webhook secret',
    description:
      'Startup default for the webhook signing secret. The Settings page overrides this at runtime without restart.',
    group: 'notifications',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: false,
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'TELEGRAM_BOT_TOKEN',
    label: 'Telegram bot token',
    description: 'Bot token used to send Telegram notifications.',
    group: 'notifications',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'TELEGRAM_WEBHOOK_SECRET',
    label: 'Telegram webhook secret',
    description: 'Optional secret used to validate Telegram webhook callbacks.',
    group: 'notifications',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'TELEGRAM_CHAT_ID',
    label: 'Telegram chat ID',
    description:
      'Startup default for the Telegram chat. The Settings page overrides this at runtime without restart.',
    group: 'notifications',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: false,
  },
  {
    key: 'TELEGRAM_GATEWAY_ENABLED',
    label: 'Telegram gateway',
    description: 'Allow Telegram users to create and continue Agent Workbench sessions.',
    group: 'notifications',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'TELEGRAM_MODE',
    label: 'Telegram gateway mode',
    description: 'Use webhook when TELEGRAM_WEBHOOK_URL is set, otherwise polling.',
    group: 'notifications',
    kind: 'select',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'auto',
    options: [
      { value: 'auto', label: 'auto' },
      { value: 'polling', label: 'polling' },
      { value: 'webhook', label: 'webhook' },
    ],
  },
  {
    key: 'TELEGRAM_WEBHOOK_URL',
    label: 'Telegram webhook URL',
    description: 'Public Telegram webhook endpoint, usually PUBLIC_BASE_URL/api/telegram/webhook.',
    group: 'notifications',
    kind: 'url',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'TELEGRAM_ALLOWED_USERS',
    label: 'Telegram allowed users',
    description:
      'Comma-separated Telegram numeric user IDs or usernames allowed to use the agent gateway.',
    group: 'notifications',
    kind: 'csv',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'TELEGRAM_ALLOW_ALL_USERS',
    label: 'Allow all Telegram users',
    description: 'Disable Telegram user allowlist checks. Use only for trusted private bots.',
    group: 'notifications',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'TELEGRAM_GROUP_ALLOWED_CHATS',
    label: 'Telegram allowed group chats',
    description: 'Comma-separated Telegram group/supergroup chat IDs allowed to use the gateway.',
    group: 'notifications',
    kind: 'csv',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'TELEGRAM_REQUIRE_MENTION',
    label: 'Require Telegram mention',
    description:
      'Require group messages to mention or reply to the bot before the gateway responds.',
    group: 'notifications',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'true',
  },
  {
    key: 'TELEGRAM_DEFAULT_PROJECT_ID',
    label: 'Telegram default project ID',
    description: 'Registered project ID used when Telegram starts a new agent session.',
    group: 'notifications',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'TELEGRAM_DEFAULT_PROJECT_PATH',
    label: 'Telegram default project path',
    description: 'Registered project path used when Telegram starts a new agent session.',
    group: 'notifications',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'TELEGRAM_DEFAULT_DEVICE_ID',
    label: 'Telegram default device ID',
    description:
      'Device used for Telegram-created sessions. Use host to target the local host device.',
    group: 'notifications',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'host',
  },
  {
    key: 'TELEGRAM_DEFAULT_EXECUTOR',
    label: 'Telegram default executor',
    description: 'Executor used for new Telegram-created sessions.',
    group: 'notifications',
    kind: 'select',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'codex',
    options: [
      { value: 'codex', label: 'codex' },
      { value: 'claude-code', label: 'claude-code' },
      { value: 'mock', label: 'mock' },
      { value: 'custom-command', label: 'custom-command' },
    ],
  },
  {
    key: 'TELEGRAM_DEFAULT_MODE',
    label: 'Telegram default mode',
    description: 'Workbench mode used for new Telegram-created sessions.',
    group: 'notifications',
    kind: 'select',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'agent',
    options: [
      { value: 'agent', label: 'agent' },
      { value: 'plan', label: 'plan' },
      { value: 'review', label: 'review' },
    ],
  },
  {
    key: 'TELEGRAM_DEFAULT_PERMISSION_MODE',
    label: 'Telegram default permissions',
    description: 'Permission preset used for new Telegram-created sessions.',
    group: 'notifications',
    kind: 'select',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'default',
    options: [
      { value: 'read-only', label: 'read-only' },
      { value: 'default', label: 'default' },
      { value: 'auto-review', label: 'auto-review' },
      { value: 'full-access', label: 'full-access' },
    ],
  },
  {
    key: 'TELEGRAM_STREAMING_ENABLED',
    label: 'Telegram streaming',
    description:
      'Reserved switch for edit-in-place Telegram streaming. Final messages are always sent.',
    group: 'notifications',
    kind: 'boolean',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: 'false',
  },
  {
    key: 'TELEGRAM_STREAM_EDIT_INTERVAL_MS',
    label: 'Telegram stream edit interval',
    description: 'Minimum interval between Telegram streaming message edits.',
    group: 'notifications',
    kind: 'number',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: '700',
    min: 200,
    max: 10000,
  },
  {
    key: 'TELEGRAM_CACHE_DIR',
    label: 'Telegram media cache',
    description:
      'Directory where Telegram media files are cached before being referenced in prompts.',
    group: 'notifications',
    kind: 'directory',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'TELEGRAM_MEDIA_MAX_BYTES',
    label: 'Telegram media max bytes',
    description: 'Maximum Telegram media size the gateway will download and cache.',
    group: 'notifications',
    kind: 'number',
    required: false,
    secret: false,
    restartRequired: true,
    defaultValue: '20971520',
    min: 1024,
    max: 104857600,
  },
  {
    key: 'VAPID_PUBLIC_KEY',
    label: 'VAPID public key',
    description: 'Public key for browser push notifications.',
    group: 'notifications',
    kind: 'string',
    required: false,
    secret: false,
    restartRequired: true,
  },
  {
    key: 'VAPID_PRIVATE_KEY',
    label: 'VAPID private key',
    description: 'Private key for browser push notifications.',
    group: 'notifications',
    kind: 'secret',
    required: false,
    secret: true,
    restartRequired: true,
    placeholder: 'Leave blank to keep the current value',
  },
  {
    key: 'RISK_RULES_PATH',
    label: 'Risk rules path',
    description: 'Optional risk rules file path used for tool-risk classification and guardrails.',
    group: 'security',
    kind: 'file',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
  },
  {
    key: 'LOG_FILE_PATH',
    label: 'Log file path',
    description: 'Optional file path for host logs. Leave blank to log only to stdout.',
    group: 'logging',
    kind: 'file',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
  },
  {
    key: 'LOG_FILE_KEEP_DAYS',
    label: 'Log retention days',
    description: 'Number of days to keep rotated log files when LOG_FILE_PATH is set.',
    group: 'logging',
    kind: 'number',
    required: false,
    secret: false,
    restartRequired: true,
    restartTarget: 'host',
    defaultValue: '30',
    min: 1,
    max: 3650,
  },
];

export const CONFIG_FIELD_BY_KEY = new Map(CONFIG_FIELDS.map((field) => [field.key, field]));
