import type { SlashCommand } from '@rac/shared';

export const SLASH_COMMANDS: SlashCommand[] = [
  {
    name: 'wb:help',
    description: 'Show Workbench-local commands.',
    usage: '/wb:help',
    category: 'agent',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:new',
    description: 'Start a new Workbench session for the current device.',
    usage: '/wb:new',
    category: 'session',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:clear',
    description: 'Clear the Workbench-local view for fallback executors.',
    usage: '/wb:clear',
    category: 'session',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:rename',
    description: 'Rename the current Workbench session.',
    usage: '/wb:rename <title>',
    argsSchema: '<title>',
    category: 'session',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:resume',
    description: 'Select the latest Workbench session.',
    usage: '/wb:resume',
    category: 'session',
    handler: 'frontend',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:model',
    description: 'Show or switch the Workbench model and reasoning effort for fallback executors.',
    usage: '/wb:model [model-id] [reasoning-effort]',
    argsSchema: '[model-id] [default|minimal|low|medium|high|xhigh|max]',
    category: 'model',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:models',
    description: 'List Workbench-known models available to this executor.',
    usage: '/wb:models',
    category: 'model',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:fast',
    description: 'Show or toggle Workbench Codex Fast mode state.',
    usage: '/wb:fast [on|off|status]',
    argsSchema: '[on|off|status]',
    category: 'model',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:device',
    description: 'Show the current device.',
    usage: '/wb:device',
    category: 'environment',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:executor',
    description: 'Show the current executor.',
    usage: '/wb:executor',
    category: 'environment',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:cwd',
    description: 'Show the current working directory.',
    usage: '/wb:cwd',
    category: 'environment',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:status',
    description: 'Show Workbench-local runtime state.',
    usage: '/wb:status',
    category: 'environment',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:review',
    description: 'Review the current repository diff.',
    usage: '/wb:review [focus]',
    argsSchema: '[focus]',
    category: 'agent',
    handler: 'agent-mode',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:diff',
    description: 'Open the Workbench diff review panel.',
    usage: '/wb:diff',
    category: 'agent',
    handler: 'frontend',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:discard',
    description: 'Open Workbench safe discard controls.',
    usage: '/wb:discard',
    category: 'agent',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:permissions',
    description: 'Show or switch the Workbench approval preset for fallback executors.',
    usage: '/wb:permissions [read-only|default|auto-review|full-access]',
    argsSchema: '[read-only|default|auto-review|full-access]',
    category: 'agent',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:compact',
    description: 'Create a Workbench-local compact summary for fallback executors.',
    usage: '/wb:compact',
    category: 'session',
    handler: 'frontend',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:export',
    description: 'Export the current session.',
    usage: '/wb:export',
    category: 'session',
    handler: 'frontend',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:init-claude',
    description: 'Preview optional Workbench Claude project templates.',
    usage: '/wb:init-claude',
    category: 'agent',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:plan',
    description: 'Start a Workbench plan-mode prompt.',
    usage: '/wb:plan [prompt]',
    argsSchema: '[prompt]',
    category: 'agent',
    handler: 'agent-mode',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:checkpoint',
    description: 'Record a native provider file checkpoint when available.',
    usage: '/wb:checkpoint [title]',
    argsSchema: '[title]',
    category: 'session',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:rewind',
    description: 'Rewind Claude Code file changes to a native checkpoint.',
    usage: '/wb:rewind [latest|provider-user-message-id] [--dry-run]',
    argsSchema: '[latest|provider-user-message-id] [--dry-run]',
    category: 'session',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
  {
    name: 'wb:stop',
    description: 'Stop the current streaming run.',
    usage: '/wb:stop',
    category: 'agent',
    handler: 'host',
    source: 'workbench',
    enabled: true,
  },
];

export function parseSlashCommand(input: string): { name: string; args: string } | null {
  const trimmed = input.trim();
  if (!trimmed.startsWith('/')) {
    return null;
  }

  const body = trimmed.slice(1);
  const firstSpace = body.search(/\s/);
  if (firstSpace === -1) {
    return { name: body.toLowerCase(), args: '' };
  }

  return {
    name: body.slice(0, firstSpace).toLowerCase(),
    args: body.slice(firstSpace).trim(),
  };
}
